### ISSUE TITLE
package.json defines project root even if higher than .env

### ISSUE THREAD

**Issue by nafg** [sastraxi/pgsh#103]
> Operating System and Version

Ubuntu 21.10

> `pgsh --version`

0.12.0

Not sure if this is a bug or something that should be changed, or "user error."

Recently when I was trying out docusaurus, yarn got confused and for some reason created or convinced me to create a package.json in my home directory. I think it something to do with my home directory being a filesystem root.

Anyway it doesn't matter, somehow I had a dummy package.json file in my home directory. My project is a Scala project using SBT and Mill build tools, so it doesn't have any of the files listed in https://github.com/sastraxi/pgsh/blob/master/src/util/find-project-root.js except `.env`. Apparently the way that logic works, if it finds a package.json in any ancestor directory that takes precedence over say a pom.xml in a closer ancestor directory.

As a result, pgsh was suddenly complaining that I didn't have a .env file, which got me really confused. I renamed them and ran pgsh init, and then pgsh current was working. When I found where it had created .env and .pgshrc, that gave me the clue that led to me finding the cause of the issue.

Possible resolutions:
1. None, this is user error
2. When pgsh can't find .env it tells me which directory it looked for it in, and why or how to change that
3. The logic in https://github.com/sastraxi/pgsh/blob/master/src/util/find-project-root.js should be changed so that the nearest one wins, or different file types have higher weights (for example, an existing .pgshrc file should win a more distant ancestor directory with a package.json)
4. Add more build tool detection (for Mill that would be a `build.sc`, for SBT `*.sbt` but usually `build.sbt`)

**Comment by sastraxi** [comment]
I think a combination of 2 and 3 is the winner here -- we should be explicit in our error messages, and it makes sense that the nearest `.pgshrc` file should win if there's one in an ancestor folder. I'll noodle on this a bit but feel free to open a PR if you have the time (I'll likely get to this in the next couple weeks otherwise).

If we just added a `dirOf('.pgshrc')` as the top of `findProjectRoot` would that solve it for you?

**Comment by nafg** [comment]
I already solved it, by deleting the rogue package.json IIRC, so whatever makes the most sense to you is good

**Comment by sastraxi** [comment]
Fixed in [d7e7afd](https://github.com/sastraxi/pgsh/commit/d7e7afde0ee80bdbb554ea8e971f976f016cc17e) and released as v0.12.1.
