### ISSUE TITLE
Directly support config files other than .env (e.g. django settings files)

### ISSUE THREAD

**Issue by mattIZB** [sastraxi/pgsh#9]
I created a .pgshrc file in my project directory. 

When running `pgsh url` it returns `undefined` as the response

When running `pgsh psql` the message response is 

```

/Users/<my_user_name_goes_here>/.nvm/versions/node/v8.12.0/lib/node_modules/pgsh/node_modules/yargs/yargs.js:1163
      else throw err
           ^

TypeError: REGEX_DATABASE_URL.exec is not a function or its return value is not iterable
    at explodeUrl (/Users/<my_user_name_goes_here>/.nvm/versions/node/v8.12.0/lib/node_modules/pgsh/src/db.js:38:26)
    at Object.thisDb (/Users/<my_user_name_goes_here>/.nvm/versions/node/v8.12.0/lib/node_modules/pgsh/src/db.js:49:3)
    at Object.exports.builder.yargs [as builder] (/Users/<my_user_name_goes_here>/.nvm/versions/node/v8.12.0/lib/node_modules/pgsh/src/cmd/psql.js:12:19)
    at Object.runCommand (/Users/<my_user_name_goes_here>/.nvm/versions/node/v8.12.0/lib/node_modules/pgsh/node_modules/yargs/lib/command.js:188:35)
    at Object.parseArgs [as _parseArgs] (/Users/<my_user_name_goes_here>/.nvm/versions/node/v8.12.0/lib/node_modules/pgsh/node_modules/yargs/yargs.js:1078:30)
    at Object.get [as argv] (/Users/<my_user_name_goes_here>/.nvm/versions/node/v8.12.0/lib/node_modules/pgsh/node_modules/yargs/yargs.js:1012:21)
    at Object.<anonymous> (/Users/<my_user_name_goes_here>/.nvm/versions/node/v8.12.0/lib/node_modules/pgsh/src/index.js:36:3)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
```

**Comment by mattIZB** [comment]
I'm on MacOS

**Comment by sastraxi** [comment]
Do you have a .env file as well? My apologies for the unclear documentation: that's where it's expecting to find a DATABASE_URL=postgres://... entry. How does your app get its db config right now? Essentially pgsh aims to read/write this value, wherever it is.

**Comment by sastraxi** [comment]
@mattIZB try upgrading to `pgsh@0.3.4` and see if the error messages are clearer. I've also updated the README with better setup instructions.

**Comment by mattIZB** [comment]
@sastraxi Is it possible to change this package so that it doesn't require a `.env` file?

Typically `.env` files are used only in node base projects (at least that's been my experience). This leaves out all other projects, that use their own setup files. 

I can create a .env file but I dont think it should be necessary to make this platform agnostic. 

I think a good solution would be that pgsh can check if a .env file exists, if it does, it will use the value from there. If not, it will read whatever value is set in the `.pgshrc` file

**Comment by sastraxi** [comment]
@mattIZB the issue with storing the connection string in `.pgshrc` is that this file is intended to be committed to version control. We'd potentially be leaking secrets as these can contain passwords. Plus, this means that your app environment and that used by pgsh can get out-of-sync, which means `pgsh` really isn't making your life more convenient anymore.

What kind of setup file does your project use?  I can see a case for having `.env` as one possible backend, with others available too. Having said that, `.env` bridges are available for pretty much every environment now (even IntelliJ!), so this might not be the right use of resources.

Would love to hear a bit more about how you get your db config to your application code right now.

**Comment by mattIZB** [comment]
ah, I didn't realize that the .pgshrc is intended to be checked into source control. 

We use django so we have the standard django setting files that read from OS environment variables. 

.env bridges do exist for django but we don't really have a need for them. 

Perhaps then a viable alternative is to add the capability for .pgshrc to read from OS environment variables in addition to .env files?

**Comment by sastraxi** [comment]
Using the OS environment would solve the read- part, but not the write-part (as setting them varies from shell to shell, as well as the inability to set for all shells / on next login / etc.). I'm also reading [here](https://docs.djangoproject.com/en/2.1/topics/settings/) that django settings files can contain arbitrary python code, so I don't know if it makes sense to try to modify them from a tool.

For now, I suggest that you try using one of the `.env` bridges that you were referring to if you'd like to use pgsh with django (https://github.com/joke2k/django-environ looks cool!), but I'll keep this issue open to track the idea of different env backends.

**Comment by sastraxi** [comment]
For 1.0, we're only going to focus on `.env`. We can re-open this later on when it's feasible to do this, but I don't think django settings files will ever be modified programmatically.
